from enum import Enum


class RevenueEventType(str, Enum):
    PAYMENT_FAILURE = "PAYMENT_FAILURE"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    OVERDUE_RECEIVABLE = "OVERDUE_RECEIVABLE"


class CustomerSegment(str, Enum):
    FIRST_TIME = "FIRST_TIME"
    LOYAL = "LOYAL"
    PREMIUM = "PREMIUM"
    HABITUAL_NON_PAYER = "HABITUAL_NON_PAYER"


class SubscriptionStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAST_DUE = "PAST_DUE"
    CANCELLED = "CANCELLED"


class RecoveryCaseStatus(str, Enum):
    DETECTED = "DETECTED"
    DIAGNOSED = "DIAGNOSED"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    EXECUTED = "EXECUTED"
    STOPPED = "STOPPED"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class ComplianceResult(str, Enum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"


class RecoveryRightTreatment(str, Enum):
    RETRY = "RETRY"
    GRACE_PERIOD = "GRACE_PERIOD"
    SOFT_REMINDER = "SOFT_REMINDER"
    ESCALATE = "ESCALATE"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    STOP = "STOP"


class ActionType(str, Enum):
    RETRY = "RETRY"
    WAIT = "WAIT"
    REMINDER = "REMINDER"
    ESCALATE = "ESCALATE"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    STOP = "STOP"


class ChannelType(str, Enum):
    PAYMENT = "PAYMENT"
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    SYSTEM = "SYSTEM"
    HUMAN = "HUMAN"


class ActionStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class DecisionMode(str, Enum):
    AI = "AI"
    RULE = "RULE"
    FALLBACK = "FALLBACK"


class AuditEventType(str, Enum):
    CASE_DETECTED = "CASE_DETECTED"
    DIAGNOSIS_COMPLETED = "DIAGNOSIS_COMPLETED"
    COMPLIANCE_CHECKED = "COMPLIANCE_CHECKED"
    RECOVERY_RIGHTS_APPLIED = "RECOVERY_RIGHTS_APPLIED"
    SCORE_CALCULATED = "SCORE_CALCULATED"
    DECISION_MADE = "DECISION_MADE"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_FAILED = "ACTION_FAILED"
    CASE_STOPPED = "CASE_STOPPED"
    AUDIT_CREATED = "AUDIT_CREATED"


class ActorType(str, Enum):
    SYSTEM = "SYSTEM"
    AI = "AI"
    RULE = "RULE"
    HUMAN = "HUMAN"


class BatchStrategy(str, Enum):
    BASELINE = "BASELINE"
    NIRNAY_PAY = "NIRNAY_PAY"
